# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dev.dance (a site for projects and stuff)
email: xhaydenbusiness@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This site is pretty stupid. Don't use it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "dev.dance" # the base hostname & protocol for your site
twitter_username: sorryigtg
github_username:  xHayden

# Build settings
markdown: kramdown
